### ISSUE TITLE
Change IGBT to other Manufacturer

### ISSUE THREAD

**Issue by bca759577** [naoto64/Three-phase-inverter#1]
Can I Change IGBT to Toshiba GT50J341?
I compared it and found that the specifications of the two IGBTs are similar.
But the Current Collector of GT50J341 is slightly higher. (GT50J341=50A  RJH60D0DPK=45A)

**Comment by naoto64** [comment]
Since it says Dedicated to Current-Resonant Inverter, I cannot recommend it, but I think it can be replaced because the characteristics themselves are almost the same.
However, when replacing, it is necessary to change R1 to R6 of igbt_module to 39Ω.
